"""Core models for Tool Gateway: AuthContext, ToolCall, ToolResult, AuditEvent."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from app.tools.enums import RiskLevel, Role, ToolStatus


class AuthContext(BaseModel):
    """
    Trusted authentication context - MUST be generated by backend.
    
    WARNING: In production, this MUST come from JWT/Session validation,
    NOT from request body or model output. The current DemoAuthContextFactory
    is for development only.
    """

    requester_id: str = Field(..., description="Authenticated user ID")
    role: Role = Field(..., description="User role")
    active_persona_id: str | None = Field(
        None, description="For resident: their own persona ID"
    )
    authorized_persona_ids: set[str] = Field(
        default_factory=set,
        description="For caregiver/family: personas they can access",
    )
    session_id: str = Field(..., description="Current session ID")
    request_id: str = Field(..., description="Unique request ID for this turn")

    model_config = {"frozen": True}


class ToolCall(BaseModel):
    """Tool invocation request from the model."""

    tool_call_id: str = Field(..., description="Unique ID for this tool call")
    name: str = Field(..., description="Tool name")
    arguments: dict[str, Any] = Field(
        default_factory=dict, description="Tool arguments from model"
    )
    idempotency_key: str | None = Field(
        None, description="Client-provided idempotency key for writes"
    )
    confirmation_token: str | None = Field(
        None, description="Token for confirming high-risk operations"
    )

    model_config = {"extra": "forbid"}


class ToolResult(BaseModel):
    """Result of tool execution."""

    tool_call_id: str = Field(..., description="Corresponding tool call ID")
    tool_name: str = Field(..., description="Tool that was invoked")
    status: ToolStatus = Field(..., description="Execution status")
    success: bool = Field(..., description="Whether operation succeeded")
    message: str = Field(
        ..., description="Human-readable message suitable for model consumption"
    )
    record_id: str | None = Field(None, description="Created/affected record ID")
    error_code: str | None = Field(None, description="Error code if failed")
    requires_confirmation: bool = Field(
        False, description="Whether confirmation is needed"
    )
    confirmation_summary: str | None = Field(
        None, description="Summary to read back for confirmation"
    )
    confirmation_token: str | None = Field(
        None, description="Token to use for confirmation"
    )
    idempotency_replayed: bool = Field(
        False, description="Whether this was a replayed idempotent request"
    )
    started_at: datetime = Field(..., description="When execution started")
    finished_at: datetime | None = Field(None, description="When execution finished")
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional non-sensitive metadata"
    )

    model_config = {"extra": "forbid"}


class AuditEvent(BaseModel):
    """
    Minimal audit record for compliance.
    
    MUST NOT contain:
    - Argument values (only names)
    - source_text content
    - AWS credentials
    - Full health records
    - Stack traces
    """

    audit_id: str = Field(..., description="Unique audit record ID")
    timestamp: datetime = Field(..., description="When event occurred")
    request_id: str = Field(..., description="Request ID")
    session_id: str = Field(..., description="Session ID")
    requester_id: str = Field(..., description="Who made the request")
    role: Role = Field(..., description="Requester's role")
    target_persona_id: str | None = Field(None, description="Target persona if any")
    tool_name: str = Field(..., description="Tool that was invoked")
    argument_names: list[str] = Field(
        default_factory=list, description="Names of arguments (NOT values)"
    )
    decision: str = Field(..., description="Gateway decision: allow/deny/confirm")
    status: ToolStatus = Field(..., description="Final status")
    risk_level: RiskLevel = Field(..., description="Assessed risk level")
    requires_confirmation: bool = Field(False, description="Whether confirmation needed")
    error_code: str | None = Field(None, description="Error code if any")
    record_id: str | None = Field(None, description="Created record ID if any")
    duration_ms: int | None = Field(None, description="Execution duration in ms")

    model_config = {"extra": "forbid"}


class DemoAuthContextFactory:
    """
    Factory for creating AuthContext in demo/development.
    
    WARNING: This is NOT secure for production use.
    Production MUST validate JWT/Session tokens and extract
    identity from a trusted source.
    """

    @staticmethod
    def create_resident(
        requester_id: str,
        persona_id: str,
        session_id: str,
        request_id: str,
    ) -> AuthContext:
        """Create AuthContext for a resident user."""
        return AuthContext(
            requester_id=requester_id,
            role=Role.RESIDENT,
            active_persona_id=persona_id,
            authorized_persona_ids={persona_id},
            session_id=session_id,
            request_id=request_id,
        )

    @staticmethod
    def create_resident_unbound(
        requester_id: str,
        session_id: str,
        request_id: str,
    ) -> AuthContext:
        """Create AuthContext for a resident without bound persona."""
        return AuthContext(
            requester_id=requester_id,
            role=Role.RESIDENT,
            active_persona_id=None,
            authorized_persona_ids=set(),
            session_id=session_id,
            request_id=request_id,
        )

    @staticmethod
    def create_caregiver(
        requester_id: str,
        authorized_persona_ids: set[str],
        session_id: str,
        request_id: str,
    ) -> AuthContext:
        """Create AuthContext for a caregiver."""
        return AuthContext(
            requester_id=requester_id,
            role=Role.CAREGIVER,
            active_persona_id=None,
            authorized_persona_ids=authorized_persona_ids,
            session_id=session_id,
            request_id=request_id,
        )

    @staticmethod
    def create_family(
        requester_id: str,
        authorized_persona_ids: set[str],
        session_id: str,
        request_id: str,
    ) -> AuthContext:
        """Create AuthContext for a family member (read-only)."""
        return AuthContext(
            requester_id=requester_id,
            role=Role.FAMILY,
            active_persona_id=None,
            authorized_persona_ids=authorized_persona_ids,
            session_id=session_id,
            request_id=request_id,
        )

    @staticmethod
    def create_admin(
        requester_id: str,
        session_id: str,
        request_id: str,
    ) -> AuthContext:
        """Create AuthContext for an admin (demo: all access)."""
        return AuthContext(
            requester_id=requester_id,
            role=Role.ADMIN,
            active_persona_id=None,
            authorized_persona_ids=set(),  # Admin checked separately
            session_id=session_id,
            request_id=request_id,
        )
